version: "3.1"

services:

  kheops-reverse-proxy:
    ports:
      - 80:8042

  pacs-arc:
    ports:
      - 8080:8080

  pacs-postgres:
    ports:
      - 5433:5432

  kheops-postgres:
    ports:
      - 5432:5432

  kheops-authorization:
    extra_hosts:
      - keycloak:host-gateway
